version: "3"

services:
  nest:
    build: .
    image: "node:12-alpine"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
      - port=3000
      - soap_port=8000
      - version=1.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8000:8000"
    tty: true
    # expose:
    #   - "3000"
    #   - "8000"
    command: "npm start"